export const SIT_NF = {
  DIGITADA: "DG",
  PROCESSADA: "PR",
  CANCELADA: "CA",
} as const;

export const SIT_ORCAMENTO_OS = {
  ABERTO: "AB",
  AGUARDANDO_APROVACAO: "AA",
  APROVADO: "AP",
  PROCESSADO: "PR",
  CANCELADO: "CA",
  ROMANEIO: "RO",
  FATURADO_PARCIAL: "FP",
  ORDEM_PRODUCAO: "OP",
} as const;

export const SIT_ORCAMENTO_FUNIL_COMERCIAL = [
  SIT_ORCAMENTO_OS.AGUARDANDO_APROVACAO,
  SIT_ORCAMENTO_OS.APROVADO,
  SIT_ORCAMENTO_OS.PROCESSADO,
  SIT_ORCAMENTO_OS.FATURADO_PARCIAL,
] as const;

export const SIT_ORCAMENTO_CONVERSAO = [
  SIT_ORCAMENTO_OS.APROVADO,
  SIT_ORCAMENTO_OS.PROCESSADO,
  SIT_ORCAMENTO_OS.FATURADO_PARCIAL,
  SIT_ORCAMENTO_OS.ROMANEIO,
] as const;
